ElemeFE/v-charts

docs/line.md, examples/pages/test.vue, src/packages/line/main.js
- add: line chart xAxisType attribute
=> 新增：折线图增加x轴类型配置

docs/props.md, examples/pages/test.vue, src/core.js
- add: chart width watch while init
=> 修改：图表生成时宽度的watch

.github/PULL_REQUEST_TEMPLATE.md
- pr need to add suitable label
=> 修改：pr template

.github/PULL_REQUEST_TEMPLATE.md, docs/map.md, examples/data/map.js, src/packages/map/main.js, src/utils.js
- add: customize data source for map chart, fix #76
=> 新增：地图组件增加自定义数据源

docs/index.html
=> docs: evaluate tool

src/core.js
=> feat: make `events` prop reactive

docs/install.md, package.json, yarn.lock
- edit: docsify and cdn example for single chart.
=> 修改：docsify 引入方式及增加单图的 cdn 引入示例

examples/pages/test.vue, src/core.js, src/packages/line/main.js
- add tooltipFormatter settings
=> feat(line): add tooltipFormatter settings

docs/candle.md, docs/gauge.md, docs/sidebar.md, examples/data/gauge.js, examples/data/index.js, examples/pages/chart.vue, src/component-list.js, src/index.es.js, src/packages/gauge/index.js, src/packages/gauge/main.js, src/packages/index/index.js, test/index.js, test/load/cdn/gauge/index.html, test/load/webpack/guage/App.vue, test/load/webpack/guage/index.js, test/load/webpack/guage/webpack.config.js
- add: gauge chart fix #116 #126
=> feat(chart): 新增仪表盘

docs/map.md, examples/data/map.js, src/packages/map/main.js
- add map settings for special area. fix #171 .
=> feat(map): 新增 specialArea 属性

examples/pages/test.vue, src/core.js
- fix: dynamic switch theme. #178
=> fix(theme): 增加 theme 和 themeName 的动态切换

docs/sidebar.md, docs/tree.md, examples/data/index.js, examples/data/tree-data.js, examples/data/tree.js, examples/pages/chart.vue, src/component-list.js, src/index.es.js, src/packages/index/index.js, src/packages/tree/index.js, src/packages/tree/main.js
=> feat(tree): 新增树图

.travis.yml, docs/install.md, package.json
- change echarts dependence type
=> fix(dependence): 将 echarts 从 dependences 修改为 peerDependences

docs/index.html
=> docs(i18n): internationalize for doc evaluating tool

examples/pages/test.vue, src/core.js
- add: ready and ready-once hook.
=> feat(core): 新增 ready 和 ready-once 钩子

docs/en/map.md, docs/map.md, examples/pages/test.vue, src/core.js, src/packages/map/main.js
- add local map import , fix #230
=> feat(map): 增加本地地图引入

docs/en/props.md, docs/props.md, examples/pages/test.vue, src/core.js
- split unused watcher of props, fix #258 .
=> fix(prop): 排除不需要 watch 的属性，增加 debounce

docs/bmap.md, src/core.js
closed #279
- fix after config once bug fixed #279
=> fix(bmap): fix after config once

docs/bmap.md, docs/en/bmap.md, examples/index.html, examples/pages/bmap.vue, src/packages/amap/main.js, src/packages/bmap/main.js
- add useOuterMap attr to amap/bmap settings. fixed #291 .
=> feat(bmap): 增加全局引入地图依赖

build/rollup.config.js, docs/index.html, package.json, src/core.js, src/utils.js, yarn.lock
=> feat(core): 增加 numerify 格式化数值

docs/en/README.md, docs/install.md
=> docs: update numerify cdn link

docs/en/README.md, docs/install.md
=> docs: update numerify link in demo

build/rollup.config.js, docs/en/README.md, docs/index.html, docs/install.md, package.json, test/load/cdn/all/index.html, test/load/cdn/bmap/index.html, test/load/cdn/candle/index.html, test/load/cdn/gauge/index.html, test/load/cdn/heatmap/index.html, test/load/cdn/line/index.html, yarn.lock
=> fix: numerify break change

examples/router.js, examples/test/number-format.vue, src/packages/amap/index.js, src/packages/bar/index.js, src/packages/bmap/index.js, src/packages/candle/index.js, src/packages/chart/index.js, src/packages/funnel/index.js, src/packages/gauge/index.js, src/packages/heatmap/index.js, src/packages/histogram/index.js, src/packages/line/index.js, src/packages/map/index.js, src/packages/pie/index.js, src/packages/radar/index.js, src/packages/ring/index.js, src/packages/sankey/index.js, src/packages/scatter/index.js, src/packages/tree/index.js, src/packages/waterfall/index.js
add numerify attr to comp, fix #360
=> feat(core): 增加 numerify 句柄到组件

examples/test/resize.vue, src/core.js
add echarts resize logic for width/height change.
=> feat(core): 增加 echarts 响应 width，height 变化

build/rollup.config.js
修复bug
[https://github.com/ElemeFE/v-charts/issues/374#issuecomment-397887078](https://github.com/ElemeFE/v-charts/issues/374#issuecomment-397887078)
=> 修复打包commonjs的压缩文件（common.min.js）时，依赖包（utils、core、constants）未能加载到的bug

docs/en/funnel.md, docs/funnel.md, examples/data/funnel.js, src/packages/funnel/main.js
add filterZero and useDefaultOrder for funnel chart fix #373
=> feat(funnel): 增加 filterZero 和 useDefaultOrder 属性

src/constants.js, src/core.js, src/modules/animation.js, src/modules/extend.js, src/modules/mark.js
add extend, mark, animation module.
=> feat(core): 将 extend, mark, animation 模块化

docs/en/props.md, docs/props.md, examples/test/resize.vue, src/core.js
- feat: add resize checker, fixed #388 .
=> feat(core): 增加 resize 时的容器检测

docs/ring.md
The previous setup mode will cause the chart to display abnormal.(Chinese)
doc:  [设置环图半径](https://v-charts.js.org/#/ring?id=%E8%AE%BE%E7%BD%AE%E7%8E%AF%E5%9B%BE%E5%8D%8A%E5%BE%84) update. The previous setup mode will cause the chart to display abnormal.
=> Repair writing error (Chinese doc)

src/packages/heatmap/main.js
=> fix(heatmap): display error while data us empty

docs/en/props.md, docs/props.md, src/core.js
add log prop for more convient debug
=> feat(core): add log prop to comp
